### ISSUE TITLE
NI AVTORJEV

### ISSUE THREAD

**Issue by evajuvanc** [MlakarT/vislice#1]
Vsak dober projekt mora našteti svoje avtorje!

Stori to v datoteki `README.md` in naštej avotrje tako:

- prvi
- drugi
- tretji

**Comment by MlakarT** [comment]
# ODGOVOR:
lažeš, ja pa so.

**Comment by evajuvanc** [comment]
Ne zgleda tko.

![image](https://user-images.githubusercontent.com/104837694/166465135-4070edf6-d334-4bed-9e0c-c9b34e8512f9.png)

**Comment by MlakarT** [comment]
Ta repo ni najbl proper ker nerabi bit in zato tud ne bo meu avtorjev lp.
###EEEEEEEE
